version: '3'

services:
  summarizer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FILES_DIRECTORY=./summaries
    volumes:
      - summaries:/summaries-examples

volumes:
  summaries: